// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: switchLights.proto

package com.caiotayota.smartwatch.switchLights;

public interface SwitchLightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:switchLights.SwitchLightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool light = 1;</code>
   */
  boolean getLight();
}
