// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: switchLights.proto

package com.caiotayota.smartwatch.switchLights;

public final class SwitchLightsServiceImpl {
  private SwitchLightsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_switchLights_SwitchLightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_switchLights_SwitchLightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_switchLights_SwitchLightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_switchLights_SwitchLightResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022switchLights.proto\022\014switchLights\"#\n\022Sw" +
      "itchLightRequest\022\r\n\005light\030\001 \001(\010\"1\n\023Switc" +
      "hLightResponse\022\032\n\022switchLightMessage\030\001 \001" +
      "(\t2k\n\023SwitchLightsService\022T\n\013switchLight" +
      "\022 .switchLights.SwitchLightRequest\032!.swi" +
      "tchLights.SwitchLightResponse\"\000BC\n&com.c" +
      "aiotayota.smartwatch.switchLightsB\027Switc" +
      "hLightsServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_switchLights_SwitchLightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_switchLights_SwitchLightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_switchLights_SwitchLightRequest_descriptor,
        new java.lang.String[] { "Light", });
    internal_static_switchLights_SwitchLightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_switchLights_SwitchLightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_switchLights_SwitchLightResponse_descriptor,
        new java.lang.String[] { "SwitchLightMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
