// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: switchLights.proto

package com.caiotayota.smartwatch.switchLights;

public interface SwitchLightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:switchLights.SwitchLightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string switchLightMessage = 1;</code>
   */
  java.lang.String getSwitchLightMessage();
  /**
   * <code>string switchLightMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getSwitchLightMessageBytes();
}
