// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepMonitoring.proto

package com.caiotayota.smartwatch.sleepMonitoring;

public interface HeartRateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sleepMonitoring.HeartRateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double heartBeatPerSecond = 1;</code>
   */
  double getHeartBeatPerSecond();
}
