// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepMonitoring.proto

package com.caiotayota.smartwatch.sleepMonitoring;

public interface heartRateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sleepMonitoring.heartRateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string heartRate = 1;</code>
   */
  java.lang.String getHeartRate();
  /**
   * <code>string heartRate = 1;</code>
   */
  com.google.protobuf.ByteString
      getHeartRateBytes();
}
