// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepMonitoring.proto

package com.caiotayota.smartwatch.sleepMonitoring;

public interface heartRateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sleepMonitoring.heartRateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 heartBeat = 1;</code>
   */
  int getHeartBeat();

  /**
   * <code>int32 seconds = 2;</code>
   */
  int getSeconds();
}
