// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepMonitoring.proto

package com.caiotayota.smartwatch.sleepMonitoring;

public interface HeartRateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sleepMonitoring.HeartRateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double heartRate = 1;</code>
   */
  double getHeartRate();
}
