// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepMonitoring.proto

package com.caiotayota.smartwatch.sleepMonitoring;

public interface MovementsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sleepMonitoring.MovementsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string totalMovementsMessage = 1;</code>
   */
  java.lang.String getTotalMovementsMessage();
  /**
   * <code>string totalMovementsMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getTotalMovementsMessageBytes();
}
