// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepMonitoring.proto

package com.caiotayota.smartwatch.sleepMonitoring;

public interface MovementRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sleepMonitoring.MovementRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool movement = 1;</code>
   */
  boolean getMovement();
}
