// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepMonitoring.proto

package com.caiotayota.smartwatch.sleepMonitoring;

public final class SleepMonitoringImpl {
  private SleepMonitoringImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sleepMonitoring_MovementRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sleepMonitoring_MovementRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sleepMonitoring_MovementsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sleepMonitoring_MovementsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025sleepMonitoring.proto\022\017sleepMonitoring" +
      "\"#\n\017MovementRequest\022\020\n\010movement\030\001 \001(\010\"2\n" +
      "\021MovementsResponse\022\035\n\025totalMovementsMess" +
      "age\030\001 \001(\t2q\n\026SleepMonitoringService\022W\n\rt" +
      "rackMovement\022 .sleepMonitoring.MovementR" +
      "equest\032\".sleepMonitoring.MovementsRespon" +
      "se(\001BB\n)com.caiotayota.smartwatch.sleepM" +
      "onitoringB\023SleepMonitoringImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sleepMonitoring_MovementRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sleepMonitoring_MovementRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sleepMonitoring_MovementRequest_descriptor,
        new java.lang.String[] { "Movement", });
    internal_static_sleepMonitoring_MovementsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sleepMonitoring_MovementsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sleepMonitoring_MovementsResponse_descriptor,
        new java.lang.String[] { "TotalMovementsMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
