// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepMonitoring.proto

package com.caiotayota.smartwatch.sleepMonitoring;

public interface TotalMovementsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sleepMonitoring.TotalMovementsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string totalMovements = 1;</code>
   */
  java.lang.String getTotalMovements();
  /**
   * <code>string totalMovements = 1;</code>
   */
  com.google.protobuf.ByteString
      getTotalMovementsBytes();
}
