// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voiceMessage.proto

package com.caiotayota.smartwatch.voiceMessage;

public interface VoiceMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:voiceMessage.VoiceMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bytes voiceMessageReceived = 1;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getVoiceMessageReceivedList();
  /**
   * <code>repeated bytes voiceMessageReceived = 1;</code>
   */
  int getVoiceMessageReceivedCount();
  /**
   * <code>repeated bytes voiceMessageReceived = 1;</code>
   */
  com.google.protobuf.ByteString getVoiceMessageReceived(int index);
}
