// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voiceMessage.proto

package com.caiotayota.smartwatch.voiceMessage;

public interface VoiceMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:voiceMessage.VoiceMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes voiceMessageReceived = 1;</code>
   */
  com.google.protobuf.ByteString getVoiceMessageReceived();
}
