// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voiceMessage.proto

package com.caiotayota.smartwatch.voiceMessage;

public final class VoiceMessageServiceImpl {
  private VoiceMessageServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_voiceMessage_VoiceMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_voiceMessage_VoiceMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_voiceMessage_VoiceMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_voiceMessage_VoiceMessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022voiceMessage.proto\022\014voiceMessage\"1\n\023Vo" +
      "iceMessageRequest\022\032\n\022voiceMessageToSend\030" +
      "\001 \001(\014\"4\n\024VoiceMessageResponse\022\034\n\024voiceMe" +
      "ssageReceived\030\001 \001(\0142v\n\023VoiceMessageServi" +
      "ce\022_\n\020sendVoiceMessage\022!.voiceMessage.Vo" +
      "iceMessageRequest\032\".voiceMessage.VoiceMe" +
      "ssageResponse\"\000(\0010\001BC\n&com.caiotayota.sm" +
      "artwatch.voiceMessageB\027VoiceMessageServi" +
      "ceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_voiceMessage_VoiceMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_voiceMessage_VoiceMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_voiceMessage_VoiceMessageRequest_descriptor,
        new java.lang.String[] { "VoiceMessageToSend", });
    internal_static_voiceMessage_VoiceMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_voiceMessage_VoiceMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_voiceMessage_VoiceMessageResponse_descriptor,
        new java.lang.String[] { "VoiceMessageReceived", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
