// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voiceMessage.proto

package com.caiotayota.smartwatch.voiceMessage;

public interface VoiceMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:voiceMessage.VoiceMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes voiceMessageToSend = 1;</code>
   */
  com.google.protobuf.ByteString getVoiceMessageToSend();
}
