// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: musicPlayer.proto

package com.caiotayota.smartwatch.musicPlayer;

public interface MusicRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:musicPlayer.MusicRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
