// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: musicPlayer.proto

package com.caiotayota.smartwatch.musicPlayer;

public interface MusicResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:musicPlayer.MusicResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string musicResponse = 1;</code>
   */
  java.lang.String getMusicResponse();
  /**
   * <code>string musicResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getMusicResponseBytes();
}
