// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepmonitoring.proto

package smartwatch.sleepmonitoring;

public interface heartRateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sleepmonitoring.heartRateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string heartRate = 1;</code>
   */
  java.lang.String getHeartRate();
  /**
   * <code>string heartRate = 1;</code>
   */
  com.google.protobuf.ByteString
      getHeartRateBytes();
}
