// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepmonitoring.proto

package smartwatch.sleepmonitoring;

/**
 * Protobuf type {@code sleepmonitoring.heartRateResponse}
 */
public  final class heartRateResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sleepmonitoring.heartRateResponse)
    heartRateResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use heartRateResponse.newBuilder() to construct.
  private heartRateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private heartRateResponse() {
    heartRate_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private heartRateResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            heartRate_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_heartRateResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_heartRateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            smartwatch.sleepmonitoring.heartRateResponse.class, smartwatch.sleepmonitoring.heartRateResponse.Builder.class);
  }

  public static final int HEARTRATE_FIELD_NUMBER = 1;
  private volatile java.lang.Object heartRate_;
  /**
   * <code>string heartRate = 1;</code>
   */
  public java.lang.String getHeartRate() {
    java.lang.Object ref = heartRate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      heartRate_ = s;
      return s;
    }
  }
  /**
   * <code>string heartRate = 1;</code>
   */
  public com.google.protobuf.ByteString
      getHeartRateBytes() {
    java.lang.Object ref = heartRate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      heartRate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHeartRateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, heartRate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHeartRateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, heartRate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof smartwatch.sleepmonitoring.heartRateResponse)) {
      return super.equals(obj);
    }
    smartwatch.sleepmonitoring.heartRateResponse other = (smartwatch.sleepmonitoring.heartRateResponse) obj;

    boolean result = true;
    result = result && getHeartRate()
        .equals(other.getHeartRate());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HEARTRATE_FIELD_NUMBER;
    hash = (53 * hash) + getHeartRate().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static smartwatch.sleepmonitoring.heartRateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartwatch.sleepmonitoring.heartRateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.heartRateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartwatch.sleepmonitoring.heartRateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.heartRateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartwatch.sleepmonitoring.heartRateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.heartRateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartwatch.sleepmonitoring.heartRateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.heartRateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static smartwatch.sleepmonitoring.heartRateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.heartRateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartwatch.sleepmonitoring.heartRateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(smartwatch.sleepmonitoring.heartRateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sleepmonitoring.heartRateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sleepmonitoring.heartRateResponse)
      smartwatch.sleepmonitoring.heartRateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_heartRateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_heartRateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartwatch.sleepmonitoring.heartRateResponse.class, smartwatch.sleepmonitoring.heartRateResponse.Builder.class);
    }

    // Construct using smartwatch.sleepmonitoring.heartRateResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      heartRate_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_heartRateResponse_descriptor;
    }

    @java.lang.Override
    public smartwatch.sleepmonitoring.heartRateResponse getDefaultInstanceForType() {
      return smartwatch.sleepmonitoring.heartRateResponse.getDefaultInstance();
    }

    @java.lang.Override
    public smartwatch.sleepmonitoring.heartRateResponse build() {
      smartwatch.sleepmonitoring.heartRateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public smartwatch.sleepmonitoring.heartRateResponse buildPartial() {
      smartwatch.sleepmonitoring.heartRateResponse result = new smartwatch.sleepmonitoring.heartRateResponse(this);
      result.heartRate_ = heartRate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof smartwatch.sleepmonitoring.heartRateResponse) {
        return mergeFrom((smartwatch.sleepmonitoring.heartRateResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(smartwatch.sleepmonitoring.heartRateResponse other) {
      if (other == smartwatch.sleepmonitoring.heartRateResponse.getDefaultInstance()) return this;
      if (!other.getHeartRate().isEmpty()) {
        heartRate_ = other.heartRate_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      smartwatch.sleepmonitoring.heartRateResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (smartwatch.sleepmonitoring.heartRateResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object heartRate_ = "";
    /**
     * <code>string heartRate = 1;</code>
     */
    public java.lang.String getHeartRate() {
      java.lang.Object ref = heartRate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        heartRate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string heartRate = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHeartRateBytes() {
      java.lang.Object ref = heartRate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        heartRate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string heartRate = 1;</code>
     */
    public Builder setHeartRate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      heartRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string heartRate = 1;</code>
     */
    public Builder clearHeartRate() {
      
      heartRate_ = getDefaultInstance().getHeartRate();
      onChanged();
      return this;
    }
    /**
     * <code>string heartRate = 1;</code>
     */
    public Builder setHeartRateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      heartRate_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sleepmonitoring.heartRateResponse)
  }

  // @@protoc_insertion_point(class_scope:sleepmonitoring.heartRateResponse)
  private static final smartwatch.sleepmonitoring.heartRateResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new smartwatch.sleepmonitoring.heartRateResponse();
  }

  public static smartwatch.sleepmonitoring.heartRateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<heartRateResponse>
      PARSER = new com.google.protobuf.AbstractParser<heartRateResponse>() {
    @java.lang.Override
    public heartRateResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new heartRateResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<heartRateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<heartRateResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public smartwatch.sleepmonitoring.heartRateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

