// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepmonitoring.proto

package smartwatch.sleepmonitoring;

public interface heartRateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sleepmonitoring.heartRateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 heartBeat = 1;</code>
   */
  int getHeartBeat();

  /**
   * <code>int32 seconds = 2;</code>
   */
  int getSeconds();
}
