// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepmonitoring.proto

package smartwatch.sleepmonitoring;

/**
 * Protobuf type {@code sleepmonitoring.MovementTracked}
 */
public  final class MovementTracked extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sleepmonitoring.MovementTracked)
    MovementTrackedOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MovementTracked.newBuilder() to construct.
  private MovementTracked(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MovementTracked() {
    movement_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MovementTracked(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            movement_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_MovementTracked_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_MovementTracked_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            smartwatch.sleepmonitoring.MovementTracked.class, smartwatch.sleepmonitoring.MovementTracked.Builder.class);
  }

  public static final int MOVEMENT_FIELD_NUMBER = 1;
  private boolean movement_;
  /**
   * <code>bool movement = 1;</code>
   */
  public boolean getMovement() {
    return movement_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (movement_ != false) {
      output.writeBool(1, movement_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (movement_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, movement_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof smartwatch.sleepmonitoring.MovementTracked)) {
      return super.equals(obj);
    }
    smartwatch.sleepmonitoring.MovementTracked other = (smartwatch.sleepmonitoring.MovementTracked) obj;

    boolean result = true;
    result = result && (getMovement()
        == other.getMovement());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MOVEMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMovement());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static smartwatch.sleepmonitoring.MovementTracked parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartwatch.sleepmonitoring.MovementTracked parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.MovementTracked parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartwatch.sleepmonitoring.MovementTracked parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.MovementTracked parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartwatch.sleepmonitoring.MovementTracked parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.MovementTracked parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartwatch.sleepmonitoring.MovementTracked parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.MovementTracked parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static smartwatch.sleepmonitoring.MovementTracked parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.MovementTracked parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartwatch.sleepmonitoring.MovementTracked parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(smartwatch.sleepmonitoring.MovementTracked prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sleepmonitoring.MovementTracked}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sleepmonitoring.MovementTracked)
      smartwatch.sleepmonitoring.MovementTrackedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_MovementTracked_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_MovementTracked_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartwatch.sleepmonitoring.MovementTracked.class, smartwatch.sleepmonitoring.MovementTracked.Builder.class);
    }

    // Construct using smartwatch.sleepmonitoring.MovementTracked.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      movement_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_MovementTracked_descriptor;
    }

    @java.lang.Override
    public smartwatch.sleepmonitoring.MovementTracked getDefaultInstanceForType() {
      return smartwatch.sleepmonitoring.MovementTracked.getDefaultInstance();
    }

    @java.lang.Override
    public smartwatch.sleepmonitoring.MovementTracked build() {
      smartwatch.sleepmonitoring.MovementTracked result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public smartwatch.sleepmonitoring.MovementTracked buildPartial() {
      smartwatch.sleepmonitoring.MovementTracked result = new smartwatch.sleepmonitoring.MovementTracked(this);
      result.movement_ = movement_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof smartwatch.sleepmonitoring.MovementTracked) {
        return mergeFrom((smartwatch.sleepmonitoring.MovementTracked)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(smartwatch.sleepmonitoring.MovementTracked other) {
      if (other == smartwatch.sleepmonitoring.MovementTracked.getDefaultInstance()) return this;
      if (other.getMovement() != false) {
        setMovement(other.getMovement());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      smartwatch.sleepmonitoring.MovementTracked parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (smartwatch.sleepmonitoring.MovementTracked) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean movement_ ;
    /**
     * <code>bool movement = 1;</code>
     */
    public boolean getMovement() {
      return movement_;
    }
    /**
     * <code>bool movement = 1;</code>
     */
    public Builder setMovement(boolean value) {
      
      movement_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool movement = 1;</code>
     */
    public Builder clearMovement() {
      
      movement_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sleepmonitoring.MovementTracked)
  }

  // @@protoc_insertion_point(class_scope:sleepmonitoring.MovementTracked)
  private static final smartwatch.sleepmonitoring.MovementTracked DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new smartwatch.sleepmonitoring.MovementTracked();
  }

  public static smartwatch.sleepmonitoring.MovementTracked getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MovementTracked>
      PARSER = new com.google.protobuf.AbstractParser<MovementTracked>() {
    @java.lang.Override
    public MovementTracked parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MovementTracked(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MovementTracked> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MovementTracked> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public smartwatch.sleepmonitoring.MovementTracked getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

