// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepmonitoring.proto

package smartwatch.sleepmonitoring;

public interface MovementTrackedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sleepmonitoring.MovementTracked)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool movement = 1;</code>
   */
  boolean getMovement();
}
