// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepmonitoring.proto

package smartwatch.sleepmonitoring;

public final class SleepMonitoringImpl {
  private SleepMonitoringImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sleepmonitoring_MovementTracked_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sleepmonitoring_MovementTracked_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sleepmonitoring_TotalMovementsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sleepmonitoring_TotalMovementsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sleepmonitoring_heartRateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sleepmonitoring_heartRateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sleepmonitoring_heartRateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sleepmonitoring_heartRateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025sleepmonitoring.proto\022\017sleepmonitoring" +
      "\"#\n\017MovementTracked\022\020\n\010movement\030\001 \001(\010\"0\n" +
      "\026TotalMovementsResponse\022\026\n\016totalMovement" +
      "s\030\001 \001(\005\"6\n\020heartRateRequest\022\021\n\theartBeat" +
      "\030\001 \001(\005\022\017\n\007seconds\030\002 \001(\005\"&\n\021heartRateResp" +
      "onse\022\021\n\theartRate\030\001 \001(\t2\322\001\n\017SleepMonitor" +
      "ing\022`\n\017movementTracker\022 .sleepmonitoring" +
      ".MovementTracked\032\'.sleepmonitoring.Total" +
      "MovementsResponse\"\000(\001\022]\n\020heartRateTracke" +
      "r\022!.sleepmonitoring.heartRateRequest\032\".s" +
      "leepmonitoring.heartRateResponse\"\000(\001B3\n\032" +
      "smartwatch.sleepmonitoringB\023SleepMonitor" +
      "ingImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sleepmonitoring_MovementTracked_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sleepmonitoring_MovementTracked_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sleepmonitoring_MovementTracked_descriptor,
        new java.lang.String[] { "Movement", });
    internal_static_sleepmonitoring_TotalMovementsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sleepmonitoring_TotalMovementsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sleepmonitoring_TotalMovementsResponse_descriptor,
        new java.lang.String[] { "TotalMovements", });
    internal_static_sleepmonitoring_heartRateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sleepmonitoring_heartRateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sleepmonitoring_heartRateRequest_descriptor,
        new java.lang.String[] { "HeartBeat", "Seconds", });
    internal_static_sleepmonitoring_heartRateResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_sleepmonitoring_heartRateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sleepmonitoring_heartRateResponse_descriptor,
        new java.lang.String[] { "HeartRate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
