// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepmonitoring.proto

package smartwatch.sleepmonitoring;

/**
 * Protobuf type {@code sleepmonitoring.TotalMovementsResponse}
 */
public  final class TotalMovementsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:sleepmonitoring.TotalMovementsResponse)
    TotalMovementsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TotalMovementsResponse.newBuilder() to construct.
  private TotalMovementsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TotalMovementsResponse() {
    totalMovements_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TotalMovementsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            totalMovements_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_TotalMovementsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_TotalMovementsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            smartwatch.sleepmonitoring.TotalMovementsResponse.class, smartwatch.sleepmonitoring.TotalMovementsResponse.Builder.class);
  }

  public static final int TOTALMOVEMENTS_FIELD_NUMBER = 1;
  private int totalMovements_;
  /**
   * <code>int32 totalMovements = 1;</code>
   */
  public int getTotalMovements() {
    return totalMovements_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (totalMovements_ != 0) {
      output.writeInt32(1, totalMovements_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (totalMovements_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, totalMovements_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof smartwatch.sleepmonitoring.TotalMovementsResponse)) {
      return super.equals(obj);
    }
    smartwatch.sleepmonitoring.TotalMovementsResponse other = (smartwatch.sleepmonitoring.TotalMovementsResponse) obj;

    boolean result = true;
    result = result && (getTotalMovements()
        == other.getTotalMovements());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTALMOVEMENTS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalMovements();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static smartwatch.sleepmonitoring.TotalMovementsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartwatch.sleepmonitoring.TotalMovementsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.TotalMovementsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartwatch.sleepmonitoring.TotalMovementsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.TotalMovementsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smartwatch.sleepmonitoring.TotalMovementsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.TotalMovementsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartwatch.sleepmonitoring.TotalMovementsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.TotalMovementsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static smartwatch.sleepmonitoring.TotalMovementsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static smartwatch.sleepmonitoring.TotalMovementsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smartwatch.sleepmonitoring.TotalMovementsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(smartwatch.sleepmonitoring.TotalMovementsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sleepmonitoring.TotalMovementsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sleepmonitoring.TotalMovementsResponse)
      smartwatch.sleepmonitoring.TotalMovementsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_TotalMovementsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_TotalMovementsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartwatch.sleepmonitoring.TotalMovementsResponse.class, smartwatch.sleepmonitoring.TotalMovementsResponse.Builder.class);
    }

    // Construct using smartwatch.sleepmonitoring.TotalMovementsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      totalMovements_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return smartwatch.sleepmonitoring.SleepMonitoringImpl.internal_static_sleepmonitoring_TotalMovementsResponse_descriptor;
    }

    @java.lang.Override
    public smartwatch.sleepmonitoring.TotalMovementsResponse getDefaultInstanceForType() {
      return smartwatch.sleepmonitoring.TotalMovementsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public smartwatch.sleepmonitoring.TotalMovementsResponse build() {
      smartwatch.sleepmonitoring.TotalMovementsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public smartwatch.sleepmonitoring.TotalMovementsResponse buildPartial() {
      smartwatch.sleepmonitoring.TotalMovementsResponse result = new smartwatch.sleepmonitoring.TotalMovementsResponse(this);
      result.totalMovements_ = totalMovements_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof smartwatch.sleepmonitoring.TotalMovementsResponse) {
        return mergeFrom((smartwatch.sleepmonitoring.TotalMovementsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(smartwatch.sleepmonitoring.TotalMovementsResponse other) {
      if (other == smartwatch.sleepmonitoring.TotalMovementsResponse.getDefaultInstance()) return this;
      if (other.getTotalMovements() != 0) {
        setTotalMovements(other.getTotalMovements());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      smartwatch.sleepmonitoring.TotalMovementsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (smartwatch.sleepmonitoring.TotalMovementsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int totalMovements_ ;
    /**
     * <code>int32 totalMovements = 1;</code>
     */
    public int getTotalMovements() {
      return totalMovements_;
    }
    /**
     * <code>int32 totalMovements = 1;</code>
     */
    public Builder setTotalMovements(int value) {
      
      totalMovements_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 totalMovements = 1;</code>
     */
    public Builder clearTotalMovements() {
      
      totalMovements_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:sleepmonitoring.TotalMovementsResponse)
  }

  // @@protoc_insertion_point(class_scope:sleepmonitoring.TotalMovementsResponse)
  private static final smartwatch.sleepmonitoring.TotalMovementsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new smartwatch.sleepmonitoring.TotalMovementsResponse();
  }

  public static smartwatch.sleepmonitoring.TotalMovementsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TotalMovementsResponse>
      PARSER = new com.google.protobuf.AbstractParser<TotalMovementsResponse>() {
    @java.lang.Override
    public TotalMovementsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TotalMovementsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TotalMovementsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TotalMovementsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public smartwatch.sleepmonitoring.TotalMovementsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

