// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sleepmonitoring.proto

package smartwatch.sleepmonitoring;

public interface TotalMovementsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sleepmonitoring.TotalMovementsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 totalMovements = 1;</code>
   */
  int getTotalMovements();
}
